version: '3.8'

services:

  konga-db:
    image: postgres:13
    container_name: konga-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: konga
      POSTGRES_DB: konga
      POSTGRES_PASSWORD: konga
    networks:
      - app-network
    volumes:
      - konga-db-data:/var/lib/postgresql/data

  konga:
    image: pantsel/konga
    container_name: kong-UI
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "1337:1337"
    environment:
      DB_ADAPTER: postgres
      DB_HOST: konga-db
      DB_PORT: 5432
      DB_USER: konga
      DB_PASSWORD: konga
      DB_DATABASE: konga
      NODE_ENV: production

  kong-database:
    image: postgres:13
    container_name: kong-database
    restart: unless-stopped
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    networks:
      - app-network
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  kong-migrations:
    image: kong/kong-gateway:latest
    container_name: kong-migrations
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - app-network
    restart: on-failure

  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    restart: unless-stopped
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PORTAL: on
      KONG_PORTAL_GUI_HOST: localhost:8003
      KONG_PORTAL_API_URL: http://localhost:8004
    ports:
      - "8000:8000"   # Proxy (HTTP)
      - "8443:8443"   # Proxy (HTTPS)
      - "8001:8001"   # Admin API
      - "8444:8444"   # Admin API (HTTPS)
      - "8002:8002"   # Dev Portal Admin API
      - "8003:8003"   # Kong Manager GUI
      - "8004:8004"   # Dev Portal GUI
    networks:
      - app-network

volumes:
  kong-db-data:
  konga-db-data:

networks:
  app-network:
    driver: bridge
    external: true
